// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_cache

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DelCacheData provides a mock function with given fields: ctx, groupKey
func (_m *Repository) DelCacheData(ctx context.Context, groupKey string) error {
	ret := _m.Called(ctx, groupKey)

	if len(ret) == 0 {
		panic("no return value specified for DelCacheData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, groupKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
