// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/vukieuhaihoa/bookmark-worker/internal/app/model"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateBatchBookmarks provides a mock function with given fields: ctx, bookmarks
func (_m *Repository) CreateBatchBookmarks(ctx context.Context, bookmarks []*model.Bookmark) error {
	ret := _m.Called(ctx, bookmarks)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchBookmarks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.Bookmark) error); ok {
		r0 = rf(ctx, bookmarks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBookmark provides a mock function with given fields: ctx, _a1
func (_m *Repository) CreateBookmark(ctx context.Context, _a1 *model.Bookmark) (*model.Bookmark, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Bookmark) (*model.Bookmark, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Bookmark) *model.Bookmark); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Bookmark) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
