// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bookmark "github.com/vukieuhaihoa/bookmark-worker/internal/app/service/bookmark"

	mock "github.com/stretchr/testify/mock"

	model "github.com/vukieuhaihoa/bookmark-worker/internal/app/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateBatchBookmarks provides a mock function with given fields: ctx, importMsg
func (_m *Service) CreateBatchBookmarks(ctx context.Context, importMsg *bookmark.ImportMessage) error {
	ret := _m.Called(ctx, importMsg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchBookmarks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bookmark.ImportMessage) error); ok {
		r0 = rf(ctx, importMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBookmark provides a mock function with given fields: ctx, url, description, userID
func (_m *Service) CreateBookmark(ctx context.Context, url string, description string, userID string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, url, description, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, url, description, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, url, description, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, url, description, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
